django/myproject/blog/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.get_redirect1),
    path('google/', views.get_redirect2),

    path('postlist/', views.post_list, name="list"),
    path('<int:post_id>/', views.post_detail, name="detail"),
    path('json/', views.json_test, name="jsontest"),
    path('exceldown/', views.excel_download, name="excel"),
    path('csvdown/', views.pandas_csv),

    path('aa/', views.test1),
    path('bb/', views.test2),
    url(r'^article/(?P<year>[0-9]{4})/$', views.test3),
    re_path(r'^article2/(?P<year>[0-9]{4})/$', views.test4),
    path('article3/<int:year>/', views.test5),
    url(r'^article/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', views.test6),
]

django/myproject/book/urls.py
from django.urls import path
from . import views

app_name = "book"

urlpatterns = [
    path('', views.book_list, name="list"),
    path('<pk>/detail/', views.book_detail, name="detail"),
    path('<pk>/edit/', views.book_edit, name="edit"),
    path('<pk>/delete/', views.book_delete, name="delete"),
    path('new/', views.book_new, name="new"),

]

django/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import HttpResponse, redirect
from django.conf import settings
from django.conf.urls.static import static

def root(request):
    return redirect('shop:list')
    # return HttpResponse("ROOT 입니다.(초기화면)")

# 앱의 urls을 등록한다.
urlpatterns = [
    # path('', root),
    path('', lambda r : redirect('shop:list')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('scoops/', include('scoops.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('shop/', include('shop.urls')),
    path('book/', include('book.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/myproject/book/models.py
from django.db import models
from django.shortcuts import reverse
from django import forms
from django.core.validators import MinLengthValidator

def minlength5_validator(value):
    if len(value) < 5:
        raise forms.ValidationError('5자리 이상만 입력가능!')


class Book(models.Model):
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=50, validators=[MinLengthValidator(3)])
    publisher = models.CharField(max_length=50, validators=[minlength5_validator])
    publication_date = models.DateField(auto_now_add=True)
    ip = models.CharField(max_length=20)
    photo = models.ImageField(blank=True)
    photo2 = models.ImageField(blank=True, upload_to='book')
    photo3 = models.ImageField(blank=True, upload_to='book/%Y/%m/%d')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
		# return reverse("book:list")
        return reverse("book:detail", kwargs={"pk": self.id})


class BookModelForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'publisher', 'photo', 'photo2', 'photo3']
        labels = {'title':'ModelForm 제목', 'author':'ModelForm 저자',
                'publisher':'ModelForm 출판사'}
        help_texts = {'author':'작가이름을 3자리 이상으로 입력하세요.',
                'ip':'IP주소는 자동으로 들어갑니다.'}

django/myproject/book/forms.py
from django import forms
from .models import Book

def minlength3_validator(value):
    if len(value) < 3:
        raise forms.ValidationError("3글자 이상입니다.")

class BookForm(forms.Form):
    title = forms.CharField(label="form 제목")
    author = forms.CharField(label="form 저자", validators=[minlength3_validator])
    publisher = forms.CharField(label="form 출판사", required=False)

    
    def save2(self, commit=True):
        book = Book(**self.cleaned_data)
        if commit:
            book.save()
        return book
    

django/myproject/book/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from .models import Book, BookModelForm
from .forms import BookForm

class BookListView(ListView):
    model = Book
    paginate_by=5
    template_name='book/list.html'

    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 5  # Display only 5 page numbers
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range
        return context


# book_list = ListView.as_view(model=Book, template_name='book/list.html')
book_list = BookListView.as_view()
book_detail = DeleteView.as_view(model=Book, template_name='book/detail.html')
# book_new = CreateView.as_view(model=Book, fields='__all__', template_name='book/new_form.html')
book_edit = UpdateView.as_view(model=Book, fields='__all__', template_name='book/edit_form.html')
book_delete = DeleteView.as_view(model=Book, success_url='/book/', template_name='book/confirm_del.html')
'''
def book_edit(request, pk):
    template_name = 'book/edit_form.html'
    book = get_object_or_404(Book, id=pk)
    if request.method == 'POST':
        form = BookModelForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            book = form.save(commit=False)
            book.ip = '.'.join(request.META['REMOTE_ADDR'].split('.')[:-1]) + '.99'
            book.save()
            return redirect('/book/')
    else:
        form = BookModelForm(instance=book)

    return render(request, 'book/edit_form.html', {'form':form})
'''

def book_new(request):
    template_name = 'book/new_form.html'
    if request.method == "GET":
        # form = BookForm()
        form = BookModelForm()
    else:
        print("저장한다..")
        # form = BookForm(request.POST, request.FILES)
        form = BookModelForm(request.POST, request.FILES)
        if form.is_valid():

            # ModelForm - Commit 지연
            book = form.save(commit=False)
            book.ip = request.META['REMOTE_ADDR']
            book.save()
            return redirect(reverse('book:list'))

            # 방법 5
            # Book.objects.create(**form.cleaned_data)
            # return redirect(reverse('book:list'))
            
            '''
            # 방법 4
            Book.objects.create(title = form.cleaned_data['title'],
                author = form.cleaned_data['author'],
                publisher = form.cleaned_data['publisher'])
            return redirect(reverse('book:list'))
            '''
            '''
            # 방법 3
            book = Book(title = form.cleaned_data['title'],
                author = form.cleaned_data['author'],
                publisher = form.cleaned_data['publisher'])
            book.save()
            return redirect(reverse('book:list'))
            '''
            '''
            # 방법 2
            book = Book()
            book.title = form.cleaned_data['title']
            book.author = form.cleaned_data['author']
            book.publisher = form.cleaned_data['publisher']
            book.save()
            return redirect(reverse('book:list'))
            '''
            '''
            # 방법1 
            print("request.POST : ", request.POST)
            print(form)
            print(form.cleaned_data)
            form.save2()
            return redirect(reverse('book:list'))
            '''
    
    return render(request, 'book/new_form.html', {'form':form})

django/myproject/book/templates/book/confirm_del.html
<h1>삭제확인</h1>
<form action="" method="post">
	{% csrf_token %}
	<button type="button" onclick="location.href='{% url 'book:list' %}'">아니오</button>
	<input type="submit" value="예, 삭제하겠습니다."/>
</form>

django/myproject/book/templates/book/detail.html
<h1>상세보기</h1>

ID : {{book.id}} <br>
제목 : {{book.title}}<br> 
저자 : {{book.author}} <br>
출판사 : {{book.publisher}} <br>
출판일 : {{book.publication_date}} <br>
IP : {{book.ip}} <br>

<hr>

<button onclick="location.href='{% url 'book:list' %}'">리스트로 이동</button>

<hr>

<img src='/media/13.jpg'/>
<img src='/media/{{book.photo}}'/>
{% if book.photo2 %}
    <img src='/{{book.photo2.url}}'/>
{% else %}
이미지가 없어요
{% endif %}

django/myproject/book/templates/book/edit_form.html
<h1>Book 수정</h1>
<form action="" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" value="수정하기"/>
</form>
<button onclick="location.href='{% url 'book:list' %}'">리스트로 이동</button>

django/myproject/book/templates/book/list.html
<!doctype html>
<html lang="en">

<head>
  <title>Book List</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<body>
  <h1>Book List</h1>
  <hr>
  <div class="container">
    <div class="row align-items-center justify-content-center">
      <div class="col-sm-12">
        <table class="table table-striped table-inverse table-responsive">
          <thead class="thead-dark">
            <tr>
              <th>번호</th>
              <th>제목</th>
              <th>저자</th>
              <th>출판사</th>
              <th>출판일</th>
              <th>IP</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for book in book_list %}
            <tr>
              <td>{{book.id}}</td>
              <td><a href="{% url 'book:detail' book.id %}">{{book.title}}</a></td>
              <td>{{book.author}}</td>
              <td>{{book.publisher}}</td>
              <td>{{book.publication_date}}</td>
              <td>{{book.ip}}</td>
              <td>
                <button onclick="location.href='{% url 'book:edit' book.id %}'">수정하기</button>
                <button onclick="location.href='{% url 'book:delete' book.id %}'">삭제하기</button>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="container">
    <!-- Pagination -->
    {% if is_paginated %}
    <nav>
      <ul class="pagination justify-content-center" style="margin:20px 0">
        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            <span>Prev</span>
          </a>
        </li>
        {% else %}
        <li class="disabled page-item">
          <a class="page-link" href="#">
            <span>Prev</span>
          </a>
        </li>
        {% endif %}

        {% for page in page_range %}
        <li {% if page == page_obj.number %} class="active page-item" {% endif %}>
          <a class="page-link" href="?page={{ page }}">{{ page }}</a>
        </li>
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            <span>Next</span>
          </a>
        </li>
        {% else %}
        <li {% if not page_obj.has_next %}class="disabled page-item" {% endif %}>
          <a class="page-link" href="#">
            <span>Next</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}

  </div>

  <hr>
  <button onclick="location.href='{% url 'book:new' %}'">등록하기</button>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>
</body>

</html>

django/myproject/book/templates/book/new_form.html
{% load static %}

<link rel="stylesheet" href="/static/css/test.css">
<link rel="stylesheet" href="{% static 'css/test2.css' %}">

<h1>Book 신규</h1>
<form action="" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" value="등록하기"/>
</form>
<button onclick="location.href='{% url 'book:list' %}'">리스트로 이동</button>

<hr>
<img src="/static/img/7.jpg"/>
<img src="{% static 'img/27.jpg' %}"/>