django/myproject/blog/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.get_redirect1),
    path('google/', views.get_redirect2),

    path('postlist/', views.post_list, name="list"),
    path('<int:post_id>/', views.post_detail, name="detail"),
    path('json/', views.json_test, name="jsontest"),
    path('exceldown/', views.excel_download, name="excel"),
    path('csvdown/', views.pandas_csv),

    path('aa/', views.test1),
    path('bb/', views.test2),
    url(r'^article/(?P<year>[0-9]{4})/$', views.test3),
    re_path(r'^article2/(?P<year>[0-9]{4})/$', views.test4),
    path('article3/<int:year>/', views.test5),
    url(r'^article/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', views.test6),
]

django/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import HttpResponse, redirect
from django.conf import settings
from django.conf.urls.static import static

def root(request):
    return redirect('shop:list')
    # return HttpResponse("ROOT 입니다.(초기화면)")

# 앱의 urls을 등록한다.
urlpatterns = [
    # path('', root),
    path('', lambda r : redirect('shop:list')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('scoops/', include('scoops.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('shop/', include('shop.urls')),
    path('book/', include('book.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/myproject/shop/urls.py
from django.urls import path
from . import views
from django.views.generic.base import RedirectView

app_name = 'shop'

urlpatterns = [
    path('', views.article_list, name='list'),
    # path('<id>/detail/', views.article_detail, name='detail'),
    # path('<pk>/detail/', views.article_detail, name='detail'),
    path('<pk>/detail/', views.ArticleDV.as_view(), name='detail'),
    path('mine/', views.MyView.as_view()),
    path('home/', views.HomePageView.as_view()),
    path('go/', RedirectView.as_view(url='https://docs.djangoproject.com')),
    path('go2/', RedirectView.as_view(url='/shop/home')),
    path('thanks/', views.success),
    path('contact/', views.ContactView.as_view()),
    path('new/', views.article_new, name="new"),
    path('<pk>/edit/', views.article_edit, name="edit"),
    path('<pk>/del/', views.article_del, name="del"),

    path('reversetest/', views.article_reversetest, name='rtest2'),
    path('temptest/', views.template_test, name='temptest'),

    path('insert/', views.article_insert, name='insert'),
    path('update/', views.article_update, name='update'),
    path('delete/', views.article_delete, name='delete'),
    path('test1/', views.test1, name='rtest1'),
    path('test2/', views.test2),
    path('test3/', views.test3),
    path('test4/', views.test4),
]

django/myproject/shop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.shortcuts import reverse

class Post(models.Model):

    # name = models.TextField()

    user = models.ForeignKey(settings.AUTH_USER_MODEL, 
                on_delete=models.CASCADE,
                related_name='shop_post_set')

    title = models.CharField(verbose_name="제목", max_length=100)
    content = models.TextField()
    created_at = models.DateField(auto_now_add=True) # 최초 생성 날짜 저장
    updated_at = models.DateTimeField(auto_now=True) # 갱신 날짜 및 시간 저장

STATUS_CHOICES = (
('d', 'Draft'),
('p', 'Published'),
('w', 'Withdrawn'),
)

class Article(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    def __str__(self):
        return self.title

    def get_absolute_url2(self):
        return reverse('shop:detail', args=[self.id])

    class Meta:
        ordering=['-id']

    # success_url이 없으면 자동 호출된다.
    def get_absolute_url(self):
        return reverse("shop:detail", kwargs={"pk": self.id})
    

django/myproject/shop/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

    def send_email(self):
        print("이메일을 보냅니다~~")

django/myproject/shop/views.py
from django.shortcuts import render, redirect, resolve_url, get_object_or_404
from .models import Article
from django.http import HttpResponse
from django.db.models import Q
from django.template.loader import render_to_string
from django.urls.base import reverse
from django.utils import timezone

class Person():
    def __init__(self, name):
        self.name = name

    def say_hello(self):
        return self.name + " 안녕하세요~~"
# ----------------------------------------------- #

# [ FormView ]

from .forms import ContactForm
from django.views.generic.edit import FormView

class ContactView(FormView):
    template_name = 'shop/contact.html'
    form_class = ContactForm
    success_url = '/shop/thanks' # urls.py
    def form_valid(self, form):
        print(form)
        print(form.cleaned_data)
        form.send_email()
        return super().form_valid(form)

def success(request):
    return render(request, 'shop/success.html')

# ----------------------------------------------- #

# [ CreateView, UpdateView, DeleteView ]

from django.views.generic.edit import CreateView, UpdateView, DeleteView

article_new = CreateView.as_view(model=Article, fields='__all__')

article_edit = UpdateView.as_view(model=Article, fields='__all__')

article_del = DeleteView.as_view(model=Article, success_url='/shop/')

# ----------------------------------------------- #

def template_test(request):
    article = Article.objects.get(id=1)
    myname = '성철'
    people = ['정표','왕기','아라']
    p = Person('정은')

    dt = timezone.now()
    str_dt = dt.strftime("%Y-%m-%d %H:%M:%S")
    past_dt = timezone.datetime(2018,10,22)
    future_dt = timezone.datetime(2019,5,21)

    return render(request, 'shop/template_test.html', 
                {'article':article, 'first_name':myname, 'people':people, 'person':p,
                'student_list':['std1', 'std2'], 'datetime_obj':dt,
                'dt':dt, 'sdt':str_dt, 'past_dt':past_dt, 'future_dt':future_dt,
                'value':[], 'value2':None, 'value3':['a','b','c']})

# ----------------------------------------------- #
'''
def article_list(request):
    qs = Article.objects.all()
    q = request.GET.get('q', '')
    if q:
        qs = qs.filter(title__contains=q)
    return render(request, 'shop/article_list.html',
            {'article_list':qs, 'q2':q})
'''
from django.views.generic import ListView
# article_list = ListView.as_view(model=Article, paginate_by=10)

class ArticleListView(ListView):
    model = Article
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["mymessage"] = "ListView 상속"
        context["today"] = timezone.now()
        return context

article_list = ArticleListView.as_view()
    

# ----------------------------------------------- #

def article_insert(request):
    article = Article(title='목요일', body='날씨가 더 좋아요', status='p')
    article.save()
    Article.objects.create(title='금요일', body='날씨가 더 좋아요', status='p')
    return HttpResponse("입력합니다.")
    # return redirect('/shop')

def article_update(request):
    ''' 
    # 특정 대상 한 건만 수정하기 #
    article = Article.objects.first()
    article.title = '업데이트 금요일입니다.'
    article.save()
    
    # 조건에 해당되는 데이터 수정하기 #
    article_qs = Article.objects.filter(title__contains="일")
    for article in article_qs:
        article.title = "일 => 변경완료!"
        article.save()
    '''

    article_qs = Article.objects.filter(title__contains="일")
    article_qs.update(title="미숫가루!")
    print(article_qs.query)
    
    return HttpResponse("수정합니다.")

def article_delete(request):
    # title에 4 또는 6이 포함된것은 모두 삭제
    article_qs = Article.objects.filter(Q(title__contains="4") | Q(title__contains="6"))
    article_qs.delete()
    return HttpResponse("삭제합니다.")


def article_detail(request, id):
    # instance = Article.objects.get(id=id)
    instance = get_object_or_404(Article, id=id)
    # print(instance)
    return render(request, 'shop/article_detail.html', {'article':instance})

# ----------------------------------------------- #

# article_detail() 함수를 다르게 정의해 보자.
# 하나의 틀을 만들어 놓고, 여러 모델에 적용할 수 있도록 한다.
def generate_view_fn(model):
    def view_fn(request, id):
        instance = get_object_or_404(model, id=id)
        instance_name = model._meta.model_name
        print('instance_name : ', instance_name)
        print('app_name : ', model._meta.app_label)

        template_name = '{}/{}_detail2.html'.format(model._meta.app_label, instance_name)
        print('template_name : ', template_name)

        return render(request, template_name, {instance_name:instance, })

    return view_fn

# article_detail = generate_view_fn(Article)

# ----------------------------------------------- #

# 클래스 기반 뷰 (Class-based View; CBV)
'''
class DetailView:
    def __init__(self, model):
        self.model = model

    def get_object(self, *args, **kwargs):
        return get_object_or_404(self.model, id=kwargs["id"])

    def get_template_name(self):
        instance_name = self.model._meta.model_name
        template_name = '{}/{}_detail2.html'.format(self.model._meta.app_label, instance_name)
        return template_name

    def dispatch(self, request, *args, **kwargs):
        instance_name = self.model._meta.model_name
        return render(request, self.get_template_name(), 
                {instance_name:self.get_object(*args, **kwargs)})

    @classmethod
    def as_view(cls, model):

        def view(request, *args, **kwargs):
            self = cls(model) # 모델 생성
            return self.dispatch(request, *args, **kwargs)

        return view

article_detail = DetailView.as_view(Article)
'''
from django.views.generic import DetailView

article_detail = DetailView.as_view(model=Article)

class ArticleDV(DetailView):
    model = Article

article_detail = ArticleDV.as_view()

# ----------------------------------------------- #

from django.views import View
class MyView(View):
    def get(self, request, *args, **kwargs):
        return HttpResponse("MyView의 get 메서드")

# ----------------------------------------------- #

from django.views.generic.base import TemplateView
class HomePageView(TemplateView):
    template_name = 'shop/home.html'
    
    # get_context_data() 재정의
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["article_list5"] = Article.objects.all()[:5]
        context["mymessage"] = "벌써 금요일 :("
        return context

# ----------------------------------------------- #

def article_reversetest(request):
    a = reverse('shop:list')
    print('shop:list와 같이 요청함: ', a)

    a = reverse('shop:detail', args=[1]) # '<id>/detail' => '1/detail'
    print('shop:detail과 같이 요청함: ', a)

    a = reverse('shop:detail', kwargs={'id':2}) # '<id>/detail' => '2/detail'
    print('shop:detail과 같이 요청함: ', a)

    a = reverse('shop:detail', 3) # '<id>/detail' => '3/detail'
    print('shop:detail과 같이 요청함: ', a)

    return redirect(a)
    # return redirect('shop:list')

def test1(request):
    response = render(request, 'shop/test1.html', {'mymessage':'render이용하기'})
    return response

def test2(request):
    s = render_to_string('shop/test1.html', {'mymessage':'render_to_string이용하기'})
    return HttpResponse(s)

def test3(request):
    if request.method == "GET":
        response = render(request, 'shop/csrf_input.html')
        return response
    else:
        title = request.POST['title']
        body = request.POST['body']
        status = request.POST['status']
        aa = Article(title=title, body=body, status=status)
        aa.save()
        return HttpResponse("입력합니다.")

def test4(request):
    author = request.POST['author']
    # response = render(request, 'shop/csrf_input.html')
    return HttpResponse(author)

django/myproject/shop/templates/shop/article_confirm_delete.html
<h1>삭제확인</h1>

<form action="" method="post">
    {% csrf_token %}
    <button type="button" onclick="location.href='{% url 'shop:list' %}'">아니오(버튼)</button>
    <input type="button" onclick="location.href='{% url 'shop:list' %}'" value="아니오">
    <a href="{% url 'shop:list' %}">아니오</a>
    <input type="submit" value="예, 삭제하겠습니다."/>
</form>

django/myproject/shop/templates/shop/article_detail.html
{% extends "shop/layout.html" %}

{% block title %}
상세보기:{{article.id}}
{% endblock title %}

{% block content %}
    <h1>상세보기</h1>

    {{article|linebreaks}} 
    {{article.id|linebreaks}} 
    {{article.title|linebreaks}} 
    {{article.body|linebreaks}} 
    {{article.status|linebreaks}} 
{% endblock content %}

django/myproject/shop/templates/shop/article_detail2.html
{% extends "shop/layout.html" %}

{% block title %}
상세보기:{{article.id}}
{% endblock title %}

{% block content %}
    <h1>상세보기 ========= 222</h1>

    {{article|linebreaks}} 
    {{article.id|linebreaks}} 
    {{article.title|linebreaks}} 
    {{article.body|linebreaks}} 
    {{article.status|linebreaks}} 
{% endblock content %}

django/myproject/shop/templates/shop/article_form.html
<h1>Article 신규</h1>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="입력하기"/>
</form>

django/myproject/shop/templates/shop/article_list.html
{% extends "shop/layout.html" %}

{% block title %}
    Article 목록
{% endblock title %}

{% block content %}
    <h1>Article 목록보기</h1>
    <h2>{{mymessage}} -- {{today}}</h2>
    <form action="" method="get">
        <input type="text" name="q" value="{{q2}}"/>
        <input type="submit" value="검색"/>
    </form>

    <button onclick="location.href='insert/'">입력하기</button>
    <button onclick="location.href='update/'">수정하기</button>
    <button onclick="location.href='delete/'">삭제하기</button>
    <button onclick="location.href='test1/'">reverse 연습1</button>
    <button onclick="location.href='{% url 'shop:rtest1' %}'">reverse 연습2</button>

    <hr>

    <ul>
    {% for article in article_list %}
        <li>
            {{forloop.counter0}}
            <a href="{{article.id}}/detail">{{article.title}}</a>
            <a href="{% url 'shop:detail' article.id %}">{{article.title}}</a>
            <a href="{{article.get_absolute_url2}}">{{article.title}}[reverse이용]</a>
            <button onclick="location.href='{% url 'shop:edit' article.id %}'">수정하기</button>
            <button onclick="location.href='{% url 'shop:del' article.id %}'">삭제하기</button>
        </li>
    {% endfor %}
    </ul>
{% endblock content %}

django/myproject/shop/templates/shop/contact.html
<form action="" method="post">
    {% csrf_token %}
    {% comment %} 
        form.as_p : form을 p태그로 만든다. 
    {% endcomment %}
    {{form.as_p}} 
    <input type="submit" value="전송"/>
</form>

django/myproject/shop/templates/shop/csrf_input.html
{% extends "shop/layout.html" %}

{% block content %}
    <form action="." method="POST">
        {% csrf_token %}
        <input type="text" name="title"><br>
        <input type="text" name="body"><br>
        <input type="radio" name="status" value="d" checked>Draft
        <input type="radio" name="status" value="p">Published
        <input type="radio" name="status" value="w">Withdrawn<br>

        <input type="submit" value="확인">
    </form>
{% endblock  %}

django/myproject/shop/templates/shop/home.html
<h1>HomePage // {{mymessage}}</h1>

{% for aa in article_list5 %}
    {{aa|linebreaks}}
{% endfor %}

django/myproject/shop/templates/shop/layout.html
{% extends "base.html" %}

{% block title %}

{% endblock title %}

{% block appheader %}
    <h1>shop 앱 정보입니다.</h1>
    <hr>
{% endblock appheader %}

{% block content %}

{% endblock content %}

django/myproject/shop/templates/shop/success.html
<h1>성공적으로 메일을 보냈습니다~! :)</h1>

django/myproject/shop/templates/shop/template_test.html
{% extends "shop/layout.html" %}

{% block content %}

{{article|linenumbers|linebreaks}}
{{article.title|linebreaks}}
{{first_name|linebreaks}}
{{people |linebreaks}}
{{people.0 |linebreaks}}
{{person.say_hello |linebreaks}}

{% for st in student_list %}
    {{st}}
{% empty %}
    <h1>학생정보가 없습니다..</h1>
{% endfor %}

<hr>
{% now "Y-m-d H:i" %}<br>
{% now "SHORT_DATE_FORMAT" %}<br>
{% now "SHORT_DATETIME_FORMAT" %}<br>
{% now "jS F Y H:i" %}
<hr>
{{ datetime_obj|date:"D d M Y" }}<br>
=> 'Wed 09 Jan 2008'<br>
{{ datetime_obj|date:"DATE_FORMAT" }}<br>
=> 디폴트 'N j, Y' (e.g. Feb. 4, 2003)<br>
{{ datetime_obj|date:"DATETIME_FORMAT" }}<br>
=> 디폴트 'N j, Y, P' (e.g. Feb. 4, 2003, 4 p.m.)<br>
{{ datetime_obj|date:"SHORT_DATE_FORMAT" }}<br>
=> 디폴트 'm/d/Y' (e.g. 12/31/2003)<br>
{{ datetime_obj|date:"SHORT_DATETIME_FORMAT" }}<br>
=> 디폴트 'm/d/Y P' (e.g. 12/31/2003 4 p.m.)<br>
{{ datetime_obj|time:"TIME_FORMAT" }}<br>
=> 디폴트 'P' (e.g. 4 p.m.)<br>
<hr>
{{ dt|date:'D d M Y'}} <br>
{{ dt|date:"DATE_FORMAT"}} <br>
{{ dt|date:"D d M Y" }} <br>
{{ dt|date:"DATE_FORMAT" }} <br>
{{ dt|date:"DATETIME_FORMAT" }}<br>
{{ dt|date:"SHORT_DATE_FORMAT" }} <br>
{{ dt|date:"SHORT_DATETIME_FORMAT" }} <br>
{{ dt|time:"TIME_FORMAT" }} <br>
<hr>
{{ past_dt|timesince}}<br>
{{ past_dt|timesince:dt }} <br>
{{ future_dt|timeuntil }} <br>
{{ future_dt|timeuntil:past_dt}} <br>

<hr>
1.{{ value|default:"nothing" }}<br>
2.{{ value2|default_if_none:"nothing" }}<br>
3.{{ value3|join:"//"}}<br>
4.문자길이:{{ value3|length }}<br>
5.문자길이와 조인:{% with data="파이\n썬"%}
   {{data|length}}<br>
   {{data|join:","}}
 {% endwith%}
6. {{value3|linebreaks}}
7. {{value3|random}} <br>
8. {{value3|slice:":2" }}<br>
8. {{value3|slice:":2"|length }}<br>
9. {% with data="<b>우리프로젝트</b> <button>담주</button>에  <span>시작!!!!</span>" %}<br>
   {{ data|striptags }}
 {% endwith%}
<hr>
{% with value="Joel is a slug" %}
  {{ value|truncatewords:2 }} <br>
{% endwith%}

{% with value="<p>Joel is a slug</p>" %}
  {{ value|truncatewords_html:2 }}<br>
{% endwith%}

{% with value="https://www.example.org/foo?a=b&c=d" %}
  {{ value|urlencode }} <br>
{% endwith%}


<hr>

{% lorem 3 %}
{% lorem 3 p %}
{% lorem 2 w random %}

{% endblock content %}

django/myproject/shop/templates/shop/test1.html
<h1>render와 render_to_string</h1>

<h1>{{ mymessage }}</h1>