django/dstagram/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from .views import register

urlpatterns = [
    path('login/', auth_view.LoginView.as_view(), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('register/', register, name='register'),
]

django/dstagram/config/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls.static import static
# from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo.urls')), # photo앱을 메인 페이지로 동작시킴
    path('accounts/', include('accounts.urls')),
]

# static을 사용해서 MEDIA_URL에 해당하는 주소를 가진 요청에 대해서는
# MEDIA_ROOT에서 찾아서 응답하도록 urlpatterns에 추가한다.
# Debug=True 일때만 이 구문은 동작한다.
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/dstagram/photo/urls.py
from django.urls import path
from django.views.generic.detail import DetailView

from .views import *
from .models import Photo

app_name = 'photo' # 네임스페이스로 사용되는 값

urlpatterns = [
    path('', photo_list, name='photo_list'),
    # DetailView를 인라인 코드로 작성
    # path('detail/<int:pk>/', DetailView.as_view(model=Photo,template_name='photo/detail.html'), name='photo_detail'),
    path('detail/<int:pk>/', PhotoDetailView.as_view(), name='photo_detail'),
    path('upload/', PhotoUploadView.as_view(), name='photo_upload'),
    path('delete/<int:pk>/', PhotoDeleteView.as_view(), name='photo_delete'),
    path('update/<int:pk>/', PhotoUpdateView.as_view(), name='photo_update'),
]

django/dstagram/accounts/models.py
from django.db import models

# Create your models here.

django/dstagram/photo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Photo(models.Model):
    # author 필드를 ForeignKey로 User 테이블과의 관계를 만듭니다.
    # CASCADE : 연결된 객체가 지워지면 해당 하위 객체도 같이 삭제합니다.
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_photos')

    # upload_to : 사진이 업로드 될 경로를 설정합니다. 업로드 실패 시 default 값으로 대체 합니다.
    # ImageField 를 사용하려면 "pillow" 모듈이 설치되어 있어야 합니다. (pip install pillow)
    photo = models.ImageField(upload_to='photos/%Y/%m/%d', default='photos/no_image.png')

    # 사진에 대한 설명을 저장할 텍스트 필드입니다.
    text = models.TextField()

    # 글 작성 일을 저장하기 위한 날짜시간 필드입니다.
    # auto_now_add=True : 객체가 추가될 때 자동으로 값을 설정합니다.
    created = models.DateTimeField(auto_now_add=True)

    # 글 수정 일을 저장하기 위한 날짜시간 필드입니다.
    # auto_now=True : 객체가 수정될 때마다 자동으로 값을 설정합니다.
    updated = models.DateTimeField(auto_now=True)


    class Meta:
        # 글 수정 시간을 기준으로 내림차순 정렬합니다.
        ordering = ['-updated']


    def __str__(self):
        return self.author.username + " " + self.created.strftime("%Y-%m-%d %H:%M:%S")

    # 객체의 상세 페이지의 주소를 반환하는 메서드
    def get_absolute_url(self):
        # reverse() : URL 패턴 이름을 가지고 해당 패턴을 찾아 주소를 만들어 주는 함수
        return reverse("photo:photo_detail", args=[str(self.id)])
        

django/dstagram/accounts/forms.py
from django.contrib.auth.models import User
from django import forms

class RegisterForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)

    # 장고에서 제공하는 모델의 입력 폼을 쉽게 만들 수 있다.
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']

    # "clean_필드명" 형태의 메서드.
    # 각 필드의 clean 메서드가 호출된 후에 호출되는 메서드이다.
    # 특별한 유효성 검사나 조작을 하고 싶을 때 사용한다.
    def clean_password2(self):
        # 반드시 cleaned_data에서 필드 값을 찾아서 사용해야 한다.
        cd = self.cleaned_data
        
        # password와 password2가 같은지 비교한다.
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords not matched!')
        return cd['password2']

django/dstagram/accounts/views.py
from django.shortcuts import render
from .forms import RegisterForm

def register(request):
    if request.method == 'POST':
        # POST 방식으로 전달된 데이터를 RegisterForm()으로 유효성 검사를 수행한다.
        user_form = RegisterForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False) # commit=False : DB 저장 X, 메모리 상에 객체만 생성한다.
            # set_password()를 사용해 비밀번호를 지정한다.(암호화된 상태로 저장됨.)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save() # 실제 데이터베이스에 저장
            return render(request, 'registration/register_done.html', {'new_user':new_user})
    else:
        # POST 방식이 아니라면, 입력 폼을 출력한다.
        user_form = RegisterForm()

    # POST 방식이 아닌경우 register 템플릿을 렌더링해 보여준다.
    return render(request, 'registration/register.html', {'form':user_form})

django/dstagram/photo/views.py
from django.shortcuts import render
from .models import Photo
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView
from django.shortcuts import redirect

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# 사진 목록(함수형 뷰로 생성)
@login_required
def photo_list(request):
    photos = Photo.objects.all()
    return render(request,'photo/list.html', {'photos':photos})

# 사진 업로드
class PhotoUploadView(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ['photo','text']
    template_name = 'photo/upload.html'

    def form_valid(self, form):
        # 작성자는 현재 로그인 한 사용자로 설정
        form.instance.author_id = self.request.user.id

        # 입력된 값들을 검증
        if form.is_valid():
            # 이상 없는 경우 DB에 저장하고, redirect 메서드로 메인페이지 이동
            form.instance.save()
            return redirect('/')
        else:
            return self.render_to_response({'form':form})

# 사진 삭제
class PhotoDeleteView(LoginRequiredMixin, DeleteView):
    model = Photo
    success_url = '/'
    template_name = 'photo/delete.html'

# 사진 수정
class PhotoUpdateView(LoginRequiredMixin, UpdateView):
    model = Photo
    fields = ['photo','text']
    template_name = 'photo/update.html'

# 사진 상세 정보
class PhotoDetailView(LoginRequiredMixin, DeleteView):
    model = Photo
    template_name = 'photo/detail.html'

django/dstagram/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dstagram {% block title %}{% endblock %}</title>

    <!-- Bootstrap CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>
<body>
    <div class="container">
        <header class="header clearfix">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a href="/" class="navbar-brand">Dstagram</a>
                <ul class="nav">
                    <li class="nav-item"><a href="/" class="active nav-link">Home</a></li>
                    {% comment %} 
                    사용자 인증 여부(user.is_authenticated)에 따라서, 노출되는 리스트를 다르게 설정한다.
                    1) 로그인한 경우에만, Upload 기능 활성화..
                    2) 로그인 하지 않은 경우는 Login, Singup 활성화..
                    {% endcomment %}
                    {% if user.is_authenticated %}
                        <li class="nav-item"><a href="#" class="nav-link">Welcome, {{user.get_username}}</a></li>
                        <li class="nav-item"><a href="{% url 'photo:photo_upload' %}" class="nav-link">Upload</a></li>
                        <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Logout</a></li>
                    {% else %}
                        <li class="nav-item"><a href="{% url 'login' %}" class="nav-link">Login</a></li>
                        <li class="nav-item"><a href="{% url 'register' %}" class="nav-link">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>

        {% block content %}
        {% endblock %}

        <footer class="footer">
            <p>&copy; 2019 Devnori. Powered By Django 2</p>
        </footer>
    </div>
</body>
</html>